name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze on SonarCloud
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner for .NET (locally)
        shell: bash
        run: |
          dotnet tool install dotnet-sonarscanner --tool-path ./.dotnet-tools
          echo "$(pwd)/.dotnet-tools" >> $GITHUB_PATH
      - name: Restore dependencies
        run: dotnet restore

      - name: Begin SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PATH: ${{ github.workspace }}/.dotnet-tools:${{ env.PATH }}
        shell: bash
        run: |
          dotnet sonarscanner begin \
            /k:"MKertane_DiiageCustomerApp" \
            /o:"mk-organisation" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io"
      - name: Build the project
        run: dotnet build --no-restore

      - name: End SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PATH: ${{ github.workspace }}/.dotnet-tools:${{ env.PATH }}
        shell: bash
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
